node_name: "ExinPool"
log_file: "mixin_blocks.log"
webhook:
  webhook_url: "https://webhook.exinwork.com/api/send?access_token={}"
  access_token: ""
node:
  api_url: "https://api.mixinwallet.com/getinfo?node="
  node_tag: ""
  local_node: ""
  remote_node_1: "mixin-node0.exinpool.com:8239"
  remote_node_2: "node-42.f1ex.io:1443"
mail:
  sender: ""
  password: ""
  receiver: ""
  subject: "Mixin Monitor"
  smtp_url: "smtp.exmail.qq.com"
  smtp_port: 465